name: karaburun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2874.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  go_router: ^17.1.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/transparent.png
    - assets/images/splash.png

flutter_native_splash:
  color: "#0F172A"
  image: assets/images/transparent.png # Görünmez resim
  
  android_12:
    image: assets/images/transparent.png
    color: "#0F172A"